name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue'
        stale-pr-message: 'Stale pull request'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        daysUntilStale: 60
        daysUntilClose: 7
        staleLabel: wontfix
        markComment: >
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs. Thank you
          for your contributions.
        closeComment: false
